apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-docker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/iamsebinsunny/django-docker.git'
    path: deploy
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: django-docker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true