name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2


            - name: Build and push Docker image
              run: |
                echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
                cd myproject
                docker build -t docker.pkg.github.com/${{ github.repository }}/django-docker:latest .
                docker push docker.pkg.github.com/${{ github.repository }}/django-docker:latest